### ISSUE TITLE
数据格式

### ISSUE THREAD

**Issue by sixmilesroad** [sevenold/bert_sequence_label#1]
请问分词任务输入的数据格式是。
----------------------------------------
我吃饭
OBI

你好
BI
-----------------------------

还是

----------------------------------
我 O
吃 B
饭 I

你 B
好 I
------------------------------------------

**Comment by sevenold** [comment]
第二种，就是readme里面说明的形式
![image](https://user-images.githubusercontent.com/41443157/108823525-81cf0000-75fb-11eb-8fa9-6066276dc26c.png)
